# Generated by Django 5.1.4 on 2024-12-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.TextField(max_length=50)),
                ('blog_content', models.TextField(max_length=200)),
                ('blog_thumbnail', models.ImageField(upload_to='thumbnails')),
            ],
        ),
    ]
