# Generated by Django 5.1.4 on 2024-12-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_thumbnail',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_content',
            field=models.TextField(max_length=1000),
        ),
    ]
